### ISSUE TITLE
GPU backend

### ISSUE THREAD

**Issue by amerkoleci** [roy-t/MiniEngine3#1]
Hi,
I would suggest you to take look at my recent GPU library for .NET, it will support D3D11 as well, in this case you can leverage your work and avoid maintaining GPU backend (it will support D3D12 and Vulkan as well).

https://github.com/amerkoleci/Vortice.GPU

Feel free to suggest features/ideas.

Thanks

**Comment by roy-t** [comment]
Hey Amer,

Somehow I completely missed this. Thanks for showing off your library! I'll definitely use it as inspiration. But one of the reasons I switched from MonoGame to Voritce.DirectX is that I wanted to learn DirectX beter!
